apiVersion: v2
name: orion-loadtest
version: 0.0.1
appVersion: 0.0.1
description: A Helm chart for running the orion-loadtests on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
- fiware
- orion
- orion-ld
- loadtests
sources:
- https://github.com/wistefan/orion-loadtest
dependencies:
  - name: grafana
    version: "6.2.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: notification-latency.enabled
  - name: telegraf
    version: "1.7.34"
    repository: "https://helm.influxdata.com/"
    condition: notification-latency.enabled
  - name: influxdb
    version: "4.8.10"
    repository: "https://helm.influxdata.com/"
    condition: notification-latency.enabled

maintainers:
- name: wistefan
  email: stefan.wiedemann@fiware.org
