{{- if .Values.echo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orion-loadtest.fullname" . }}-echo
  labels:
    {{ include "orion-loadtest.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "orion-loadtest.name" . }}-echo
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "orion-loadtest.name" . }}-echo
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.echo.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.echo.additionalAnnotations -}}
      annotations:
        {{- with .Values.echo.additionalAnnotations }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- end }}
    spec:
      serviceAccountName: fiware-root-runner
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.echo.image.pullPolicy }}
          image: "{{ .Values.echo.image.repository }}:{{ .Values.echo.image.tag }}"
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  {{- end }}