{{- if .Values.echo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion-loadtest.fullname" . }}-echo
  {{- if .Values.collector.service.annotations }}
  annotations:
    {{ toYaml .Values.echo.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "orion-loadtest.name" . }}-echo
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.echo.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "orion-loadtest.name" . }}-echo
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end }}