apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion-loadtest.fullname" . }}
  {{- if .Values.collector.service.annotations }}
  annotations:
    {{ toYaml .Values.collector.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{ include "orion-loadtest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.collector.service.port }}
      targetPort: {{ .Values.collector.port }}
      protocol: TCP
      name: ftp
    {{- range untilStep 21000 21010 1 }}
    - port: {{ . }}
      targetPort: {{ .}}
      protocol: TCP
      name: ftp-{{ . }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "orion-loadtest.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}