broker:
  envPrefix: ORIONLD_
  mutexPolicy: none
  maxConnections: 20000
  logging:
    level: FATAL

  reqPoolSize: 16
  db:
    hosts:
      - mongo-mongodb-0.mongo-mongodb-headless.fiware.svc.cluster.local
      - mongo-mongodb-1.mongo-mongodb-headless.fiware.svc.cluster.local
      - mongo-mongodb-2.mongo-mongodb-headless.fiware.svc.cluster.local
      - mongo-mongodb-3.mongo-mongodb-headless.fiware.svc.cluster.local
    replicaSet: rs0
    writeConcern: 0
    poolSize: 128
deployment:
  replicaCount: 4
  image:
    repository: fiware/orion-ld
    tag: 0.6.0
  resources:
    limits:
      cpu: 2
      memory: 12288Mi
    requests:
      cpu: 2
      memory: 12288Mi